name: ğŸ Bug Report for Application
description: File a bug for the Application
title: "[BUG] "
labels: ["bug ğŸ›", "App ğŸ’»"]
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Open '...'
        2. Enter '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: dropdown
    id: os-env
    attributes:
      label: Operating System / Environment
      description: Please select the operating system / Environment you are using.
      multiple: true
      options:
        - "Windows ğŸªŸ"
        - "MacOS ğŸ"
        - "Linux ğŸ§"
        - "Docker ğŸ‹"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add relevant screenshots for the bug.
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: dropdown
    id: assignee
    attributes:
      label: Do you want to work on this issue?
      multiple: false
      options:
        - "Yes"
        - "No"
      default: 0
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join our [Discord community](https://discord.gg/DeT4jXPfkG) for any help or support.